gnom_site/gnom_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .api_urls import urlpatterns as api_urlpatterns
from .yasg import urlpatterns as swagger_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gnome_main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

# captcha
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

# rest маршруты
urlpatterns += api_urlpatterns

# swagger маршруты
urlpatterns += swagger_urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

gnom_site/gnome_main/urls.py
from django.urls import path
from .views import *

app_name = 'gnome_main'

urlpatterns = [
    path('', Main.as_view(), name='main'),

    path('blog/author/<slug:slug>/filter/', AuthorPostsFilteredView.as_view(), name='blog-filter-author'),
    path('blog/author/<slug:slug>/search/', AuthorPostsSearchView.as_view(), name='blog-search-author'),
    path('blog/author/<slug:slug>/', AuthorPostsView.as_view(), name='blog-author'),

    path('blog/filter/', BlogFilterView.as_view(), name='blog-filter'),
    path('blog/search/', BlogSearchView.as_view(), name='blog-search'),
    path('blog/<slug:slug>/', PostView.as_view(), name='show-post'),
    path('blog/', BlogView.as_view(), name='blog'),

    path('login/', Login_view.as_view(), name='log-in'),
    path('logout/', Logout_view.as_view(), name='log-out'),
    path('user/<str:slug>/delete/starting/', deleteUserStarting, name='user-delete-starting'),
    path('user/<str:slug>/delete/<str:sign>/', DeleteUserView.as_view(), name='user-delete-confirm'),
    path('user/<str:slug>/change/', ChangeUserInfoView.as_view(), name='profile-change'),
    path('user/<slug:slug>/studio/<str:section>/', StudioDetailView.as_view(), name='studio-detail'),
    path('user/<slug:slug>/studio/', UserStudio.as_view(), name='studio'),
    path('user/<str:slug>/', UserProfile.as_view(), name='user-profile'),
    path('user/password/reset/confrim/<str:uidb64>/<str:token>/', PasswordResetConfrim.as_view(), name='password-reset-confrim'),
    path('user/password/reset/complete/', PasswordResetComplete.as_view(), name='password-reset-complete'),
    path('user/password/reset-done/', PasswordResetDone.as_view(), name='password-reset-done'),
    path('user/password/reset/', PasswordReset.as_view(), name='password-reset'),

    path('register/activate/<str:sign>/', user_activate, name='register-done'),
    path('register/confirm/', RegisterConfrimView.as_view(), name='register-confirm'),
    path('register/', RegisterUserView.as_view(), name='register'),

    path('report/<slug:slug>/post/', PostReportView.as_view(), name='post-report'),
    path('report/<slug:slug>/comment/<int:id>/', CommentReportView.as_view(), name='comment-report'),

    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='update-post'),
    path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='delete-post'),
    path('post/new/', PostCreateView.as_view(), name='create-post'),

    path('notifications/<slug:slug>/', NotificationView.as_view(), name='notifications'),

    path('access-denied/', AccessDenied.as_view(), name='access-denied'),

    path('favourites-likes-starting/', FavLikeStarting.as_view(), name='user-favourites-likes-starting'),
    path('favourites/', UserFavourites.as_view(), name='user-favourites'),
    path('liked/', UserLiked.as_view(), name='user-liked'),
    path('history/', UserHistory.as_view(), name='user-history'),
]

gnom_site/gnome_main/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify
from .utilities import get_image_path_post, get_image_path_post_ai, random_key

class AdvUser(AbstractUser):
    def get_profile_image_path(instance, filename):
        username = instance.username
        return f'photos/{username}/{filename}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.username}')#-{"".join(random.choices(string.ascii_lowercase, k=10))}')[:200]
        super().save(*args, **kwargs)

    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошёл активацию?')
    send_messages = models.BooleanField(default=True,
                        verbose_name='Слать оповещения о комментариях?')
    avatar = models.ImageField(verbose_name='Аватар',
                              upload_to=get_profile_image_path,
                              null=True, db_index=True)
    profile_image = models.ImageField(verbose_name='Шапка профиля',
                              upload_to=get_profile_image_path,
                              null=True, db_index=True)
    status = models.CharField(max_length=50, null=True, blank=True,
                              db_index=True, verbose_name='Статус профиля')
    description = models.CharField(max_length=500, null=True, blank=True,
                              db_index=True, verbose_name='Описание профиля')
    subscriptions = models.ManyToManyField('self', blank=True, symmetrical=False, verbose_name='Подписчики')
    slug = models.SlugField(max_length=200, unique=True, db_index=True,
                            verbose_name='Слаг')

    class Meta(AbstractUser.Meta):
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f'<{self.username}>'

    def get_absolute_url(self):
        return reverse('gnome_main:user-profile', kwargs={'slug': self.slug})

    def delete(self, *args, **kwargs):
        for post in self.post_set.all():
            post.delete()
        super().delete(*args, **kwargs)


class Rubric(models.Model):
    '''Модель рубрик'''
    name = models.CharField(max_length=30, db_index=True, unique=True,
                            verbose_name='Название')
    order = models.SmallIntegerField(default=0, db_index=True,
                                     verbose_name='Порядок')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT,
                                     null=True, blank=True,
                                     verbose_name='Надрубрика')

class SuperRubricManager(models.Manager):
    '''Менеджер надрубрик'''
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)

class SuperRubric(Rubric):
    '''Модель надрубрики'''
    objects = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = 'Надрубрика'
        verbose_name_plural = 'Надрубрики'

class SubRubricManager(models.Manager):
    '''Менеджер подрубрики'''
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)

class SubRubric(Rubric):
    '''Модель подрубрик'''
    objects = SubRubricManager()

    def __str__(self):
        return '%s - %s' % (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name',
                    'order', 'name')
        verbose_name = 'Подрубрика'
        verbose_name_plural = 'Подрубрики'

@deconstructible
class WordCountValidator(object):
    def __init__(self, count):
        self.count = count

    def __call__(self, val):
        if len(str(val).split(' ')) < self.count :
            raise ValidationError('Контент должен содержать как ' +
                        'минимум %(count)s слов',
                        code='not_enough_words',
                        params={'count': self.count})

    def __eq__(self, other):
        return self.count == other.count

class PostManager(models.Manager):
    '''Менеджер записей'''
    def get_queryset(self):
        return super().get_queryset()\
            .select_related('rubric', 'author')\
            .prefetch_related('postadditionalimage_set',
                              'postviewcount_set',
                              'postlike_set',
                              'postdislike_set',
                              'postcomment_set')

class Post(models.Model):
    '''Модель постов'''
    objects = PostManager()

    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT,
                               verbose_name='Рубрика')
    title = models.CharField(max_length=80, db_index=True,
                             verbose_name='Название')
    slug = models.SlugField(max_length=50, unique=True, db_index=True,
                            verbose_name='Слаг')
    content = models.TextField(verbose_name='Содержание',
                               validators=[MinLengthValidator(100, 'Содержание должно быть длинной минимум в 100 символов'),
                                           WordCountValidator(10)])
    preview = models.ImageField(null=True, blank=True,
                                upload_to=get_image_path_post,
                                verbose_name='Превью')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE,
                               verbose_name='Автор')
    is_active = models.BooleanField(default=True,
                                    db_index=True,
                                    verbose_name='Активна')
    tag = models.ManyToManyField('PostTag', verbose_name='Тэг')
    created_at = models.DateTimeField(auto_now_add=True,
                                      db_index=True,
                                      verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-created_at']

    def delete(self, *args, **kwargs):
        for ai in self.postadditionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.slug:
            key = random_key(20)
            self.slug = f'{self.author.slug}-{key}'[:50]
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title} - {self.author.username} - {self.created_at}'

    def get_absolute_url(self):
        return reverse('gnome_main:show-post', kwargs={'slug': self.slug})

    def get_view_count(self):
        '''Возвращает количество просмотров записи'''
        return self.postviewcount_set.count()

    def get_like_count(self):
        '''Возвращает количество лайков записи'''
        return self.postlike_set.count()

    def get_dislike_count(self):
        '''Возвращает количество дизлайков записи'''
        return self.postdislike_set.count()

    def get_comment_count(self):
        '''Возвращает количество комментариев записи'''
        return self.postcomment_set.count()

    def get_posttags(self):
        '''Возвращает все связанные с постом тэги'''
        return self.tag.all()

@deconstructible
class MaxFileSizeValidator(object):
    '''Валидотор размера дополнительного медиа'''
    # max_size указывать в мб
    def __init__(self, max_size):
        self.max_size = max_size * 1024 * 1024
        self.orig_size = max_size

    def __call__(self, value, *args, **kwargs):
        if value.size > self.max_size:
            raise ValidationError('Размер файла превышает %(max_size)s мб',
                        code='file_exceeded_size',
                        params={'max_size': self.orig_size})

    def __eq__(self, other):
        return self.max_size == other.max_size

class PostAdditionalImage(models.Model):
    '''Модель дополнительных изображений'''
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             verbose_name='Пост')
    media = models.FileField(upload_to=get_image_path_post_ai,
                             validators=[MaxFileSizeValidator(100)],
                             verbose_name='Медиа')

    class Meta:
        verbose_name = 'Медиа-файл'
        verbose_name_plural = 'Медиа-файл'

    def __str__(self):
        return f'{self.post.id}-{self.media.url}'

class PostViewCount(models.Model):
    '''Модель просмотра'''
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             verbose_name='Пост')
    ip_address = models.GenericIPAddressField(verbose_name='Ip адрес')
    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE,
                             null=True, blank=True,
                             verbose_name='Просмотревший пользователь')
    viewed_on = models.DateTimeField(auto_now_add=True,
                                     db_index=True,
                                     verbose_name='Дата просмотра')

    class Meta:
        ordering = ('-viewed_on',)
        verbose_name = 'Просмотр'
        verbose_name_plural = 'Просмотры'
        unique_together = ('post', 'user', 'ip_address')

    def __str__(self):
        return f'Просмотр. Пост: {self.post.id} - дата: {self.viewed_on}'

class PostLike(models.Model):
    '''Модель лайков поста'''
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             verbose_name='Пост')
    user = models.ForeignKey(AdvUser, on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    created_at = models.DateTimeField(auto_now_add=True,
                                      null=True,

gnom_site/gnome_main/templates/layout/basic.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link type="image/x-icon" href="{% static 'gnome_main/css/images/favicon.png' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static 'gnome_main/css/images/favicon.png' %}" rel="icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'gnome_main/css/style_basic.css' %}">
    <script src="{% static 'gnome_main/js/basic.js' %}"></script>
    {% block links %}
    {% endblock links %}
    <title>{% block title %}Правда о гномах{% endblock title %}</title>
    {% block head %}
    {% endblock head %}
</head>
<body>
<div class="header">
    <div class="container">
        <div class="header-line">
            <div class="header-logo">
                <a href="{% url 'gnome_main:main' %}" alt="main">
                    <img src="{% static 'gnome_main/css/images/logo_main.png' %}" alt="logo">
                </a>
            </div>

            <div class="nav">
                <div class="buttons">
                    <a class="nav-item" href="{% url 'gnome_main:main' %}">Главная</a>
                    <a class="nav-item" href="{% url 'gnome_main:blog' %}">Блог</a>
                    {% if not user.is_authenticated %}
                    <a class="nav-item-last" href="{% url 'gnome_main:log-in' %}">Войти</a>
                    {% endif %}
                </div>
            </div>

            {% if user.is_authenticated %}
            <div class="flex-line-container mini-icons">
                <a href="{% url 'gnome_main:notifications' slug=user.slug %}">
                    {% if notif_index %}
                    <img class="dropdown-btn pointer" src="{% static 'gnome_main/css/images/notifications_active.png' %}">
                    {% else %}
                    <img class="dropdown-btn pointer" src="{% static 'gnome_main/css/images/notifications.png' %}">
                    {% endif %}
                </a>
                <a class="last" href="{% url 'gnome_main:create-post' %}">
                    <img src="{% static 'gnome_main/css/images/addpost.png' %}">
                </a>
            </div>
            {% endif %}

            <div class="profile pointer">
                {% if not user.is_authenticated %}
                <a href="{% url 'gnome_main:log-in' %}"><img src="{% static 'gnome_main/css/images/profile_img.png' %}" alt="profile_img"></a>
                {% else %}
                <img src="{% static 'gnome_main/css/images/profile_img.png' %}" alt="profile_img" id="profile_img">
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
<div class="dropdown-list">
    <ul>
        <li><a href="{{ user.get_absolute_url }}">Мой профиль</a></li>
        <hr>
        <li><a href="{% url 'gnome_main:blog-author' slug=user.slug %}">Мои записи</a></li>
        <hr>
        <li><a href="{% url 'gnome_main:user-favourites-likes-starting' %}">Избранное</a></li>
        <hr>
        <li><a href="{% url 'gnome_main:log-out' %}">Выйти</a></li>
    </ul>
</div>
{% endif %}

<div class="main-content">
{% block content %}
{% endblock content %}
</div>

{% block footer %}
{% endblock footer %}

</body>

</html>

gnom_site/gnome_main/templates/layout/basic_footer.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block footer %}
<div class="footer">
       <div class="container">
           <div class="footer-content">
               <div class="text-header-footer">
                   <p>Контакты</p>
               </div>

               <div class="description-footer">
                   <div class="description">
                       <div class="img-f1">
                           <a href="https://www.youtube.com/channel/UC3FDstzIYKOm_0T5TkPoCvg">
                               <img src="{% static 'gnome_main/css/images/yt_black.png' %}">
                           </a>
                       </div>

                       <div class="footer-text">
                           <a href="https://www.youtube.com/channel/UC3FDstzIYKOm_0T5TkPoCvg">youtube/channel.com</a>
                       </div>
                   </div>

               <div class="description">
                   <div class="img-f2">
                       <a href="mailto:truth.about.gnomes@gmail.com">
                           <img src="{% static 'gnome_main/css/images/mail_black.png' %}">
                       </a>
                   </div>

                   <div class="footer-text">
                       <a href="mailto:truth.about.gnomes@gmail.com">truth.about.gnomes@gmail.com</a>
                   </div>
               </div>
            </div>
        </div>
    </div>
</div>
{% endblock footer %}

gnom_site/gnome_main/templates/layout/blog_basic.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load profile_extras %}
{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/post_cards.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_blog.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/paginator.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="{% static 'gnome_main/js/functions.js' %}"></script>
<script src="{% static 'gnome_main/js/blog.js' %}"></script>
<script>
    {% include 'scripts/csrf_script.html' %}
    {% include 'scripts/user_login_auth_script.html' %}
</script>
{% endblock %}

{% block content %}
<div class="content">
    <div class="open-filter">
        <img src="{% static 'gnome_main/css/images/icon_filter.png' %}">
    </div>
    <div class="filter-container">
        <form class="filter" method="get" action="{% block filter_url %}{% url 'gnome_main:blog-filter' %}{% endblock filter_url %}">
            <div class="flex-line">
                <h1>Фильтр</h1>
                <span class="close"><img src="{% static 'gnome_main/css/images/icon_xletter.png' %}"></span>
            </div>

            <div class="filter-params">
                <div class="by-date">
                    <p class="param-name">По дате</p>
                    <div class="edit">
                        <label for="from">от</label>
                        <input type="date" name="date-from" id="from">
                    </div>
                    <div class="edit">
                        <label for="to">до</label>
                        <input type="date" name="date-to" id="to">
                    </div>
                </div>
                {% block by_author %}
                <div class="by-author">
                    <p class="param-name">По автору</p>
                    <div class="edit">
                        <label for="by-author">имя</label>
                        <input type="text" name="author" id="by-author" placeholder="authorname">
                    </div>
                </div>
                {% endblock by_author %}

                <div class="by-rubric">
                    <p class="param-name">Рубрика</p>
                    <div class="checkbox-container">
                        <div class="checkbox">
                                {% for rubric in rubrics %}
                                {% ifchanged rubric.super_rubric.pk %}
                                <p class="rubric-name">{{ rubric.super_rubric.name }}</p>
                                {% endifchanged %}
                                <div class="form-label">
                                    <label class="chbox">
                                        <input type="checkbox" name="rubric" value="{{ rubric.name }}">
                                        <span></span>
                                        {{ rubric.name }}
                                    </label>
                                </div>
                                {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="another-params">
                    <p class="param-name">Другие параметры</p>
                    <div class="checkbox-container">
                        <div class="checkbox">
                            <div class="form-label form-radio">
                                <input type="radio" name="radio-filters" id="popular" value="popular">
                                <label for="popular">популярное</label>
                            </div>

                            <div class="form-label form-radio">
                                <input type="radio" name="radio-filters" id="more-views" value="more-views">
                                <label for="more-views">больше просмотров</label>
                            </div>

                            <div class="form-label form-radio">
                                <input type="radio" name="radio-filters" id="old" value="old">
                                <label for="old">старое</label>
                            </div>

                            <div class="form-label form-radio">
                                <input type="radio" name="radio-filters" id="new" value="new">
                                <label for="new">новое</label>
                            </div>
                        </div>
                    </div>
                </div>

                {% if user.is_authenticated %}
                <div class="subscriptions">
                    <p class="param-name">Подписки</p>
                    <div class="checkbox">
                        <div class="icons">
                            {% for sub in subscriptions %}
                            {% if forloop.counter0 >= 4 %}
                            <span class="icon hide" style="display: none;">
                                <a href="{{ sub.get_absolute_url }}">
                                    <img src="{{ sub.avatar.url }}">
                                </a>
                                <a href="{{ sub.get_absolute_url }}">
                                    <p>{{ sub.username }}</p>
                                </a>
                            </span>
                            {% else %}
                            <span class="icon">
                                <a href="{{ sub.get_absolute_url }}">
                                    <img src="{{ sub.avatar.url }}">
                                </a>
                                <a href="{{ sub.get_absolute_url }}">
                                    <p>{{ sub.username }}</p>
                                </a>
                            </span>
                            {% endif %}
                            {% endfor %}
                            <div class="more">
                                <button type="button" id="more">ещё</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}

                <div class="urls">
                    <p class="param-name">Полезные ссылки</p>
                    <div class="url">
                        <a href="#">
                            <img src="{% static 'gnome_main/css/images/yt_white.png' %}">
                            <p>youtube/channel.com</p>
                        </a>
                    </div>
                    <div class="url">
                        <a href="#">
                            <img src="{% static 'gnome_main/css/images/mail_white.png' %}">
                            <p>gnomestrue@gmail.com</p>
                        </a>
                    </div>
                </div>

                <div class="button-container">
                    <input type="submit" class="filter-button" value="Применить">
                </div>
            </div>
        </form>
    </div>

    <div class="posts">
        <div class="find-container">
            <div class="find-edit">
                <form id="find_" method="get" action="{% block blog_search %}{% url 'gnome_main:blog-search' %}{% endblock blog_search %}">
                    <input type="text" name="text-find" id="find_input" placeholder="Введите название записи">
                    <input type="image" src="{% static 'gnome_main/css/images/find.png' %}" alt="find-button" id="find-button">
                </form>
            </div>
        </div>

        <div class="post-container">
            {% include 'includings/posts.html' %}
        </div>
        {% include 'includings/paginator.html' %}
    </div>
</div>
{% endblock %}

gnom_site/gnome_main/templates/layout/detail_view_studio.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load profile_extras %}
{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/studio.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="https://code.highcharts.com/stock/modules/data.js"></script>
<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
<script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
<script src="https://code.highcharts.com/stock/modules/accessibility.js"></script>

<script src="{% static 'gnome_main/js/studio.js' %}"></script>

<script>
    var data = {{ data|safe }};
    var g_title = '{{ g_title }}';
    var ld_indicator = {{ ld_indicator }};
</script>
{% endblock links %}

gnom_site/gnome_main/templates/layout/fav_like_basic.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load profile_extras %}
{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/fav_like.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/post_cards.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/paginator.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="{% static 'gnome_main/js/fav_like.js' %}"></script>
<script>
    {% include 'scripts/csrf_script.html' %}
</script>
{% endblock links %}

{% block content %}
<div class="flex-line-container fl-content">
    <h1 id="pagename">{% block pagename %}{% endblock pagename %}</h1>
    <div class="post-container">
        {% include 'includings/posts_mini.html' %}
    </div>
</div>
{% include 'includings/paginator.html' %}
{% endblock content %}