gnom_site/gnom_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .api_urls import urlpatterns as api_urlpatterns
from .yasg import urlpatterns as swagger_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gnome_main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

# captcha
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

# rest маршруты
urlpatterns += api_urlpatterns

# swagger маршруты
urlpatterns += swagger_urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

gnom_site/gnome_main/urls.py
from django.urls import path
from .views import *

app_name = 'gnome_main'

urlpatterns = [
    path('', Main.as_view(), name='main'),

    path('blog/author/<slug:slug>/filter/', AuthorPostsFilteredView.as_view(), name='blog-filter-author'),
    path('blog/author/<slug:slug>/search/', AuthorPostsSearchView.as_view(), name='blog-search-author'),
    path('blog/author/<slug:slug>/', AuthorPostsView.as_view(), name='blog-author'),

    path('blog/filter/', BlogFilterView.as_view(), name='blog-filter'),
    path('blog/search/', BlogSearchView.as_view(), name='blog-search'),
    path('blog/<slug:slug>/', PostView.as_view(), name='show-post'),
    path('blog/', BlogView.as_view(), name='blog'),

    path('login/', Login_view.as_view(), name='log-in'),
    path('logout/', Logout_view.as_view(), name='log-out'),
    path('user/<str:slug>/delete/starting/', deleteUserStarting, name='user-delete-starting'),
    path('user/<str:slug>/delete/<str:sign>/', DeleteUserView.as_view(), name='user-delete-confirm'),
    path('user/<str:slug>/change/', ChangeUserInfoView.as_view(), name='profile-change'),
    path('user/<slug:slug>/studio/<str:section>/', StudioDetailView.as_view(), name='studio-detail'),
    path('user/<slug:slug>/studio/', UserStudio.as_view(), name='studio'),
    path('user/<str:slug>/', UserProfile.as_view(), name='user-profile'),
    path('user/password/reset/confrim/<str:uidb64>/<str:token>/', PasswordResetConfrim.as_view(), name='password-reset-confrim'),
    path('user/password/reset/complete/', PasswordResetComplete.as_view(), name='password-reset-complete'),
    path('user/password/reset-done/', PasswordResetDone.as_view(), name='password-reset-done'),
    path('user/password/reset/', PasswordReset.as_view(), name='password-reset'),

    path('register/activate/<str:sign>/', user_activate, name='register-done'),
    path('register/confirm/', RegisterConfrimView.as_view(), name='register-confirm'),
    path('register/', RegisterUserView.as_view(), name='register'),

    path('report/<slug:slug>/post/', PostReportView.as_view(), name='post-report'),
    path('report/<slug:slug>/comment/<int:id>/', CommentReportView.as_view(), name='comment-report'),

    path('post/update/<slug:slug>/', PostUpdateView.as_view(), name='update-post'),
    path('post/delete/<slug:slug>/', PostDeleteView.as_view(), name='delete-post'),
    path('post/new/', PostCreateView.as_view(), name='create-post'),

    path('notifications/<slug:slug>/', NotificationView.as_view(), name='notifications'),

    path('access-denied/', AccessDenied.as_view(), name='access-denied'),

    path('favourites-likes-starting/', FavLikeStarting.as_view(), name='user-favourites-likes-starting'),
    path('favourites/', UserFavourites.as_view(), name='user-favourites'),
    path('liked/', UserLiked.as_view(), name='user-liked'),
    path('history/', UserHistory.as_view(), name='user-history'),
]

gnom_site/gnome_main/views.py
from time import mktime

from django.db.models.functions import TruncDate
from django.db.models.signals import post_save
from django.dispatch import Signal
from django.utils import timezone

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.signing import BadSignature
from django.db import IntegrityError
from django.db.models import Count
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordResetDoneView
from django.template.defaultfilters import truncatewords, safe
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView, DetailView, ListView

from .forms import RegisterUserForm, ChangeUserInfoForm, DeleteUserForm, PostReportForm, CommentReportForm, \
    PostCreationForm, AIFormSet
from .mixins import BlogMixin, NotificationCheckMixin, BlogFilterMixin, BlogSearchMixin, ViewIncrementMixin, \
    CommentDispatcherMixin, RecLoaderMixin, PostInfoAddMixin, CsrfMixin, SubscribeMixin, IsPostSubscribeMixin
from .models import *
from .apps import user_delete_signal
from .templatetags.profile_extras import date_ago, post_views, is_full, comment_pluralize
from .utilities import signer, get_client_ip


##############################################################
# Сигналы
##############################################################
# Обработчик сигнала создания нового комментария
def comment_save_dispathcher(sender, **kwargs):
    if kwargs['created']:
        instance = kwargs['instance']
        post_author = instance.post.author
        if post_author != instance.user:
            title = 'c'
            message = f'Пользователь <a href="{instance.user.get_absolute_url()}" ' \
                      f'class="nametag">' \
                      f'{instance.user.username}</a> оставил комментарий под вашим ' \
                      f'постом <a href="{instance.post.get_absolute_url()}" class="nametag">' \
                      f'{instance.post.title}</a><br>' + \
                      f'Вот его текст: {instance.comment}'
            Notification.objects.create(user=post_author, title=title,
                                                    message=message)
# сигнал создания нового комментария
post_save.connect(comment_save_dispathcher, sender=SuperPostComment)
post_save.connect(comment_save_dispathcher, sender=SubPostComment)

# Обработчик сигнала создания новой жалобы на Пост
def post_report_save_dispathcher(sender, **kwargs):
    if kwargs['created']:
        instance = kwargs['instance']
        type = instance.type

        title = 'r'
        message = f'Пользователь <a href="{instance.user.get_absolute_url()}" ' \
                  f'class="nametag">' \
                  f'{instance.user.username}</a> подал жалобу на ваш пост: ' \
                  f'<a href="{instance.post.get_absolute_url()}" class="nametag">' \
                  f'{instance.post.title}</a><br>' \
                  f'Тип жалобы: {type}'
        if instance.text:
            message += f'<br>Вот текст жалобы: {instance.text}'

        Notification.objects.create(user=instance.post.author, title=title,
                                                message=message)
# сигнал создания новой жалобы на Пост
post_save.connect(post_report_save_dispathcher, sender=PostReport)

# обработчик сигнала создания новой жалобы на Комментарий
def comment_report_save_dispathcher(sender, **kwargs):
    if kwargs['created']:
        instance = kwargs['instance']
        type = instance.type

        title = 'r'
        message = f'Пользователь <a href="{instance.user.get_absolute_url()}" ' \
                  f'class="nametag">' \
                  f'{instance.user.username}</a> подал жалобу на ваш комментарий:<br>' \
                  f'{instance.comment.comment}<br>' \
                  f'Тип жалобы: {type}'
        if instance.text:
            message += f'<br>Вот текст жалобы: {instance.text}'

        Notification.objects.create(user=instance.comment.user, title=title,
                                                message=message)
# сигнал создания новой жалобы на Комментарий
post_save.connect(comment_report_save_dispathcher, sender=CommentReport)

# обработчик сигнала новой подписки
def user_subsript_notification(instance, user):
    message = f'Ваш новый подписчик: <a href={instance.get_absolute_url()} ' \
              f'class="nametag">' \
              f'{instance.username}</a>'
    Notification.objects.create(title='s', user=user, message=message)

# сигнал новой подписки на пользователя
user_subsript = Signal()

def user_subsript_dispatcher(sender, **kwargs):
    user_subsript_notification(kwargs['instance'], kwargs['user'])

user_subsript.connect(user_subsript_dispatcher)



##############################################################
# Представления
##############################################################
# Главная страница
class Main(NotificationCheckMixin, TemplateView):
    template_name = 'gnome_main/main.html'

class BlogBase:
    '''Блог базовый класс'''
    model = Post
    template_name = 'gnome_main/blog.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_active=True)
        return queryset

# Блог
class BlogView(BlogBase, NotificationCheckMixin, CsrfMixin, BlogMixin, ListView):
    '''Представление блога'''

class BlogFilterView(BlogBase, NotificationCheckMixin, CsrfMixin, BlogFilterMixin, ListView):
    '''Представление блога с фильтром'''

class BlogSearchView(BlogBase, NotificationCheckMixin, CsrfMixin, BlogSearchMixin, ListView):
    '''Представление блога с фильтром'''

class PostView(NotificationCheckMixin, ViewIncrementMixin, CommentDispatcherMixin,
               RecLoaderMixin, PostInfoAddMixin, CsrfMixin, IsPostSubscribeMixin,
               SubscribeMixin, DetailView):
    '''Представление детального просмотра поста'''
    model = Post
    template_name = 'gnome_main/show_post.html'
    context_object_name = 'post'

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        d = dict(request.POST)
        # формирования контекста
        context = {}
        # если пользователь оставил SuperComment
        if 'new_supercomment' in d:
            self.new_supercomment(context, post, d['new_supercomment'][0])
        # если пользователь оставил SubComment
        elif 'new_subcomment' in d:
            self.new_subcomment(context, post, d['new_subcomment'][0],
                                d['s-username'][0], d['super-id'][0])
        # если пользователь поставил лайк/дизлайк на комментарий
        elif 'comment-new-info' in d:
            self.comment_like_dislike(d['data'][0], d['status'][0], d['comment-new-info'][0])
        # если пользователь поставил лайк/дизлайк на пост или добавил пост в избранное
        elif 'post-new-info' in d:
            self.add_info(d['data'][0], d['status'][0], post)
        # подгрузить дополнительные НАДкомментарии
        elif 'load_supercomments' in d:
            self.load_supercomments(context, d['filter'][0], d['ids'][0], post)
        # подгрузить рекомендации
        elif 'load_rec' in d:
            self.load_rec(context, post, d['ids'][0])
        # подгрузить дополнительные ПОДкомментарии
        elif 'load_subcomments' in d:
            self.load_subcomments(context, d['super_id'][0], int(d['start_scomment'][0]),
                                  int(d['end_scomment'][0]))
        # изменить комментарий
        elif 'change_comment' in d:
            self.change_comment(context, d['с_id'][0], d['change-comment-line'][0])
        # удалить комментарий
        elif 'delete_comment' in d:
            self.delete_comment(d['c_id'][0])
        # подписаться на автора поста
        elif 'subscribe' in d:
            self.subscribe(post.author, d['subscribe'][0])

        return JsonResponse(data=context, status=200)

class UserProfile(NotificationCheckMixin, PostInfoAddMixin, SubscribeMixin, CsrfMixin, TemplateView):
    '''Представление профиля пользователя'''
    template_name = 'gnome_main/user_profile.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cur_user = get_object_or_404(AdvUser, slug=self.kwargs.get('slug'))
        count = cur_user.subscriptions.count()
        posts = Post.objects.filter(author=cur_user, is_active=True).order_by('-created_at')[:10]
        context['cur_user'] = cur_user
        context['sub_count'] = count
        context['posts_count'] = posts.count()
        context['posts'] = posts
        context['is_subscribe'] = cur_user.subscriptions.filter(id=self.request.user.id).exists()
        return context

    def post(self, request, slug):
        d = dict(request.POST)
        cur_user = get_object_or_404(AdvUser, slug=slug)
        # формирования контекста
        context = {}
        if 'subscribe' in d:
            self.subscribe(cur_user, d['subscribe'][0])
        elif 'filter' in d:
            try:
                context['posts'] = []
                if d['filter'][0] == 'popular':
                    posts = Post.objects.filter(is_active=True, author=cur_user) \
                                .distinct() \
                                .annotate(num_likes=Count('postlike'),
                                          num_dislikes=Count('postdislike'),
                                          num_comments=Count('postcomment'),

gnom_site/gnome_main/templates/gnome_main/access_denied.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
{% endblock links %}

{% block content %}
<h1 style="color: #fff; margin: 20px 0px 0px 20px;">Отказано в доступе</h1>
{% endblock content %}

gnom_site/gnome_main/templates/gnome_main/author_posts.html
{% extends 'layout/blog_basic.html' %}

{% block filter_url %}
{% url 'gnome_main:blog-filter-author' slug=author_slug %}
{% endblock filter_url %}

{% block by_author %}
<div class="by-author" style="display: none;">
    <p class="param-name">По автору</p>
    <div class="edit">
        <label for="by-author">имя</label>
        <input type="text" name="author" id="by-author" placeholder="authorname"
               value="{{author_slug}}">
    </div>
</div>
{% endblock by_author %}

{% block blog_search %}
{% url 'gnome_main:blog-search-author' slug=author_slug %}
{% endblock blog_search %}

gnom_site/gnome_main/templates/gnome_main/delete_user_starting.html
{% extends "layout/basic_footer.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/footer.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_reg_confirm.css' %}">
{% endblock %}

{% block content %}
<div class="widget">
    <div class="widget-container">
        <h1 class="text">
            Чтобы удалить ваш аккаунт, перейдите по ссылке, отправленной на вашу почту
        </h1>
    </div>
</div>
{% endblock %}

gnom_site/gnome_main/templates/gnome_main/fav_like_start.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load profile_extras %}
{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/studio.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
{% endblock links %}

{% block content %}
<div class="flex-line-container filter">
    <a class="filter-btn" href="{% url 'gnome_main:user-liked' %}">Понравившиеся</a>
    <a class="filter-btn" href="{% url 'gnome_main:user-favourites' %}">Избранное</a>
    <a class="filter-btn" href="{% url 'gnome_main:user-history' %}">История просмотров</a>
</div>
{% endblock content %}

gnom_site/gnome_main/templates/gnome_main/favourites.html
{% extends 'layout/fav_like_basic.html' %}

{% block pagename %}
Избранное
{% endblock pagename %}

gnom_site/gnome_main/templates/gnome_main/login.html
{% extends "layout/basic_footer.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/footer.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_log_in.css' %}">
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1>Вы уже выполнили вход</h1>
{% else %}
<div class="widget">
    <div class="widget-container">
        <h1>Введите данные</h1>
        <form method="post" class="login">
            {% csrf_token %}
            <div class="info">
                {{ form.as_p }}
            </div>
            <div>
                <a href="{% url 'gnome_main:password-reset' %}" class="form-a">Забыли пароль?</a>
                <a class="form-btn-a" href="{% url 'gnome_main:register' %}">Регистрация</a>
                <input type="submit" value="Войти" class="form-btn">
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

gnom_site/gnome_main/templates/gnome_main/post_create.html
{% extends 'layout/post_cud.html' %}

gnom_site/gnome_main/templates/gnome_main/post_delete.html
{% extends "layout/basic_footer.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/footer.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_log_in.css' %}">
{% endblock %}

{% block content %}
<div class="widget">
    <div class="widget-container">
        <h1>Вы точно хотите удалить запись "{{ object.title }}" ?</h1>
        {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{{ message }}{% endif %}
        {% endfor %}
        {% endif %}
        <form method="post" class="login">
            {% csrf_token %}
            <div class="info">
                {% for field in form %}
                    <p>
                        {{ field.label }}
                        {{ field }}
                    </p>
                {% endfor %}
            </div>
            <div class="flex-line-container">
                <a class="form-btn-a" style="text-decoration:none;" href="{% url 'gnome_main:update-post' slug=object.slug %}">Назад</a>
                <input type="submit" value="Удалить" class="form-btn">
            </div>
        </form>
    </div>
</div>
{% endblock %}

gnom_site/gnome_main/templates/gnome_main/register.html
{% extends "layout/basic_footer.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/footer.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_log_in.css' %}">
{% endblock %}

{% block content %}
<div class="widget">
    <div class="widget-container">
        <h1>Введите данные</h1>
        <form method="post" id="user-form">
            {% csrf_token %}
            <div class="info">
            {{ form.as_p }}
            </div>
            <div>
                <a href="{% url 'gnome_main:main' %}" class="form-a">На главную</a>
                <a class="form-btn-a" href="{% url 'gnome_main:log-in' %}">Войти</a>
                <input type="submit" value="Зарегистрироваться" class="form-btn">
            </div>
        </form>
    </div>
</div>
{% endblock %}

gnom_site/gnome_main/templates/gnome_main/register_complete.html
{% extends "layout/basic_footer.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/style_basic_nfixed_withFooter.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_reg_confrim.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="widget">
    <div class="widget-container">
        <h1 class="text">
            Регистрация завершена!
        </h1>
        <a href="{% url 'gnome_main:log-in' %}">Войти</a>
    </div>
</div>
{% endblock %}

gnom_site/gnome_main/templates/gnome_main/show_post.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load profile_extras %}
{% load thumbnail %}

{% block links %}
<link rel="stylesheet" href="{% static 'gnome_main/css/header_nfixed.css' %}">
<link rel="stylesheet" href="{% static 'gnome_main/css/style_show_post.css' %}">
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script src="{% static 'gnome_main/js/functions.js' %}"></script>
<script src="{% static 'gnome_main/js/show_post.js' %}"></script>
<script>
    {% include 'scripts/csrf_script.html' %}
    {% include 'scripts/user_login_auth_script.html' %}
</script>
{% endblock %}

{% block content %}
<div style="display: none; width: 500px;" id="deletion">
	<h2>Вы точно хотите удалить этот комментарий ?</h2>
    <div class="flex-line-container flex-space-between">
        <button type="button" class="deletion-btn" id="btn-delete-yes">Да</button>
        <button type="button" class="deletion-btn" id="btn-delete-no">Нет</button>
    </div>
</div>

<div style="display: none; width: 500px;" id="deletion_complete">
	<h2>Комментарий удалён</h2>
    <div class="flex-line-container end">
        <button type="button" class="deletion-btn" id="btn-ok">Ок</button>
    </div>
</div>

<div class="main-container">
    <div class="post">
        <div class="flex-line-container author-date">
            <h1>{{ post.title }}</h1>
            {% if user.is_authenticated %}
            <div class="add-dropdown">
                <img src="{% static 'gnome_main/css/images/triple_dots_white.png' %}" class="adddrop-post pointer">
                <div class="post-dropdown dropdown">
                    <ul>
                        {% if post.author.id == user.id %}
                        <li><a href="{% url 'gnome_main:update-post' slug=slug %}">Изменить</a></li>
                        {% else %}
                        <li>
                            <a href="{% url 'gnome_main:post-report' slug=slug %}">
                                <img src="{% static 'gnome_main/css/images/report.png' %}">
                                Пожаловаться
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="flex-line-container author-date">
            <div class="flex-line-container author-data-aub">
                <span class="comment-icon">
                    <a href="{{ post.author.get_absolute_url }}">
                        <img src="{{ post.author.avatar.url }}">
                    </a>
                </span>
                <a href="{{ post.author.get_absolute_url }}">
                    <p class="author-name">{{ post.author.username }}</p>
                </a>
                <div>
                {% if user.is_authenticated %}
                    {% if is_subscribe %}
                        <button type="button" class="sub-true">Отписаться</button>
                        <button type="button" class="sub-false" style="display: none;">Подписаться</button>
                        {% elif is_subscribe == False and user != post.author %}
                        <button type="button" class="sub-false">Подписаться</button>
                        <button type="button" class="sub-true" style="display: none;">Отписаться</button>
                        {% elif user == post.author %}
                        <a href="{% url 'gnome_main:update-post' slug=post.slug %}" class="change-post">Изменить</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'gnome_main:log-in' %}">
                        <p type="button" class="sub-false" style="margin:0;">Подписаться</p>
                    </a>
                {% endif %}
                </div>
            </div>
            <p>{{ post.created_at|date_ago }}</p>
        </div>
        <div class="flex-line-container wrap">
            {% for image in post.postadditionalimage_set.all %}
                <a href="{{ image.media.url }}" data-fancybox="gallery" data-caption="Медиа-файл №{{ forloop.counter }}" class="small-margin-r">
                    {% if image.media|is_video_preview %}
                    <img src="{{ image.media|is_video_preview }}"/>
                    {% else %}
                    <img src="{{ image.media|thumbnail_url:'default' }}"/>
                    {% endif %}
                </a>
            {% endfor %}
        </div>
        <div class="content">
            <p>
                {{ post.content|safe }}
            </p>
        </div>

        <div class="flex-line-container space-between">
            <div class="flex-line-container info">
                <img src="{% static 'gnome_main/css/images/views_white.png' %}" class="icon">
                <p>{{ post.get_view_count|post_views }}</p>
            </div>
            <div class="flex-line-container likes">
                <div class="flex-line-container info">
                    <p>{{ post.get_like_count }}</p>
                    {% if post.postlike_set|is_full:user.id %}
                    <img src="{% static 'gnome_main/css/images/likes_white_full.png' %}" class="icon-l like-main pointer">
                    {% else %}
                    <img src="{% static 'gnome_main/css/images/likes_white.png' %}" class="icon-l like-main pointer">
                    {% endif %}
                </div>
                <div class="flex-line-container info">
                    <p>{{ post.get_dislike_count }}</p>
                    {% if post.postdislike_set|is_full:user.id %}
                    <img src="{% static 'gnome_main/css/images/dislikes_white_full.png' %}" class="icon-l dislike-main pointer">
                    {% else %}
                    <img src="{% static 'gnome_main/css/images/dislikes_white.png' %}" class="icon-l dislike-main pointer">
                    {% endif %}
                </div>
                <div class="flex-line-container info">
                    {% if post.postfavourite_set|is_full:user.id %}
                    <img src="{% static 'gnome_main/css/images/favourite_white_full.png' %}" class="icon-l favourite pointer">
                    {% else %}
                    <img src="{% static 'gnome_main/css/images/favourite_white.png' %}" class="icon-l favourite pointer">
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="flex-line-container comments">
            <p id="comments-count-post">{{ post.get_comment_count|comment_pluralize }}</p>
            <div class="flex-line-container info" style="display: flex;">
                <div class="flex-line-container filter pointer">
                    <img src="{% static 'gnome_main/css/images/comment_filter.png' %}" class="icon">
                    <p>Упорядочить</p>
                </div>
                <div class="filters dropdown-filter" style="display: none;">
                    <button type="button" class="filter-btn pointer" id="new">Новые</button>
                    <button type="button" class="filter-btn pointer" id="old">Старые</button>
                    <button type="button" class="filter-btn pointer" id="popular">Популярные</button>
                    {% if user.is_authenticated %}
                    <button type="button" class="filter-btn pointer" id="my">Мои</button>
                    {% endif %}
                    <span class="close-filters">
                        <img src="{% static 'gnome_main/css/images/icon_xletter.png' %}">
                    </span>
                </div>
            </div>
        </div>

        <div class="flex-line-container error-div" style="display: block;">
            <p class="error-p"></p>
        </div>

        <div class="flex-line-container comment-line">
            <span class="comment-icon">
                {% if user.is_authenticated %}
                <a href="{{ user.get_absolute_url }}">
                    <img src="{{ user.avatar.url }}">
                </a>
                {% else %}
                <a href="{% url 'gnome_main:log-in' %}">
                    <img src="{% static 'gnome_main/css/images/not_auth_user_avatar.png' %}">
                </a>
                {% endif %}
            </span>
            <form id="main-comment" method="post">
                {% csrf_token %}
                <textarea type="text" rows="3" name="main-comment-line" class="c-line" placeholder="Ввести комментарий..." autocomplete="off"></textarea>
                <div class="flex-line-container comment-btns">
                    <button type="button" id="cancel-btn" class="pointer">Отмена</button>
                    <button type="submit" class="last pointer">Отправить</button>
                </div>
            </form>
        </div>

        <div class="comment-all"></div>
    </div>
    <div class="recomendation">
        <h1 style="font-weight: normal;">Похожие</h1>
    </div>
{% endblock %}